version: "3.8"

services:
  prompt-bloom-studio:
    build:
      context: .
      dockerfile: ./PromptCrafter-Docker/Dockerfile
      pull_policy: build
    container_name: prompt-bloom-studio
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
    env_file:
      - .env
    volumes:
      - ./PromptCrafter-Docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - prompt-network

networks:
  prompt-network:
    driver: bridge
