version: "3.8"

services:
  prompt-bloom-studio:
    image: ghcr.io/${GITHUB_USER}/prompt-bloom-studio:latest
    container_name: prompt-bloom-studio
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - prompt-network

networks:
  prompt-network:
    driver: bridge
