version: "3.8"

services:
  prompt-bloom-studio:
    build:
      context: .
      dockerfile: ./PromptCrafter-Docker/Dockerfile
      args:
        NODE_ENV: production
    container_name: prompt-bloom-studio
    ports:
      - "7777:80"
      - "7778:443"
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    env_file:
      - .env
    volumes:
      - ./PromptCrafter-Docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Remove the dist volume mount as it's overriding the built files from Dockerfile
    networks:
      - prompt-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
    security_opt:
      - no-new-privileges:true

networks:
  prompt-network:
    driver: bridge
