version: '3.8'

services:
  prompt-bloom-studio:
    build:
      context: ..
      dockerfile: ./PromptCrafter-Docker/Dockerfile
    container_name: prompt-bloom-studio
    ports:
      - "8080:80"
    restart: unless-stopped
    # Environment variables
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - prompt-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    security_opt:
      - no-new-privileges:true

networks:
  prompt-network:
    driver: bridge